# Generated by Django 5.2.4 on 2025-07-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='ID único do dispositivo ESP8266 (ex: ESP8266_B001)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Nome descritivo para o dispositivo (ex: Sensor Sala)', max_length=100, verbose_name='Nome Amigável')),
                ('device_type', models.CharField(blank=True, help_text='Categoria do dispositivo (ex: Temperatura, Relé, IR)', max_length=50, null=True, verbose_name='Tipo de Dispositivo')),
                ('location', models.CharField(blank=True, help_text='Onde o dispositivo está localizado (ex: Sala, Quarto)', max_length=100, null=True, verbose_name='Localização')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Data e hora da última comunicação do dispositivo', verbose_name='Última Conexão')),
                ('is_online', models.BooleanField(default=False, help_text='Indica se o dispositivo está online', verbose_name='Online')),
                ('data', models.JSONField(blank=True, help_text='Dados genéricos recebidos do dispositivo (temperatura, umidade, etc.)', null=True, verbose_name='Dados Recebidos')),
                ('last_command', models.CharField(blank=True, help_text='O último comando enviado para o dispositivo', max_length=255, null=True, verbose_name='Último Comando')),
                ('last_command_at', models.DateTimeField(blank=True, help_text='Data e hora em que o último comando foi enviado', null=True, verbose_name='Último Comando Em')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro do dispositivo', verbose_name='Criado Em')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['name'],
            },
        ),
    ]
