# Generated by Django 5.2.4 on 2025-07-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_communication',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dayofweek',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='dayofweek',
            name='numeric_value',
            field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], unique=True, verbose_name='Valor Numérico'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(help_text='ID único do dispositivo ESP8266 (ex: ESP8266_B001)', max_length=100, unique=True, verbose_name='ID do Dispositivo'),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='command_json',
            field=models.JSONField(help_text='Comando a ser enviado no formato JSON (ex: {"action": "ligar_rele", "target": "rele_D1", "value": 1})', verbose_name='Comando JSON'),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='day_of_week',
            field=models.ManyToManyField(blank=True, help_text='Selecione os dias da semana para agendamentos semanais.', to='devices.dayofweek', verbose_name='Dia da Semana'),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='devices',
            field=models.ManyToManyField(help_text='Selecione os dispositivos que receberão este comando.', related_name='scheduled_commands', to='devices.device', verbose_name='Dispositivos'),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Marque para ativar o agendamento.', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='last_triggered_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora da última vez que este agendamento foi acionado.', null=True, verbose_name='Última Execução'),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='name',
            field=models.CharField(help_text='Nome descritivo para o agendamento (ex: Ligar Luz da Sala)', max_length=255, verbose_name='Nome do Comando'),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='run_once_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora para executar o comando apenas uma vez.', null=True, verbose_name='Executar Uma Vez Em'),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='schedule_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('once', 'Once')], default='weekly', help_text='Tipo de agendamento: Diário (todos os dias), Semanal (dias específicos), Uma Vez (data e hora únicas).', max_length=50, verbose_name='Tipo de Agendamento'),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='time_of_day',
            field=models.TimeField(blank=True, help_text='Hora (HH:MM:SS) para o comando ser enviado.', null=True, verbose_name='Hora do Dia'),
        ),
    ]
