# Generated by Django 5.2.4 on 2025-07-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_command_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o último comand foi enviado', null=True, verbose_name='Último Comando Em'),
        ),
    ]
