# Generated by Django 5.2.4 on 2025-07-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_last_command_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='pending_command',
            field=models.JSONField(blank=True, help_text="Comando a ser enviado para o dispositivo (JSON: {'action': 'ligar', 'target': 'rele'})", null=True, verbose_name='Comando Pendente'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_command',
            field=models.CharField(blank=True, help_text='O último comando que o dispositivo executou.', max_length=255, null=True, verbose_name='Último Comando Executado'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_command_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o último comando foi executado pelo dispositivo.', null=True, verbose_name='Executado Em'),
        ),
    ]
