# Generated by Django 5.2.4 on 2025-07-29 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_last_communication_alter_dayofweek_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='last_communication',
        ),
    ]
