# Generated by Django 5.2.4 on 2025-07-29 05:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_remove_device_last_communication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['device_id'], 'verbose_name': 'Dispositivo', 'verbose_name_plural': 'Dispositivos'},
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(help_text='IP do dispositivo (ex: 192.168.10.50)', max_length=100, verbose_name='IP do Dispositivo'),
        ),
        migrations.CreateModel(
            name='DeviceDataHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_payload', models.JSONField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='devices.device')),
            ],
            options={
                'verbose_name': 'Histórico de Dados do Dispositivo',
                'verbose_name_plural': 'Históricos de Dados dos Dispositivos',
                'ordering': ['-timestamp'],
            },
        ),
    ]
