"""
Django settings for iot_monitor_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ls0!rv^(jh$o0684#x84npnak28&9_dpz5$^o)9sx#nas5r(5u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Importante tirar o '*' após finalização !!!!!!!!!!!!!!!!

ALLOWED_HOSTS = ['192.168.31.80', 'localhost', '127.0.0.1', '*']


# Application definition

INSTALLED_APPS = [
    'jazzmin', 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework', 
    'rest_framework.authtoken',
    'devices', 
    #'django_celery_beat', # <<< ADICIONE ESTA LINHA
    # 'django_celery_results', # Opcional: Para armazenar resultados de tarefas no DB
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'iot_monitor_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'iot_monitor_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / 'locale', 
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication', # Habilita autenticação por Token
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', # Apenas usuários autenticados podem acessar
        # 'rest_framework.permissions.AllowAny', # Se quiser permitir acesso público em algumas APIs
    ]
}


# Celery Configuration
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0' # URL do seu servidor Redis
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0' # Onde os resultados das tarefas são armazenados
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Sao_Paulo' # Ou seu fuso horário local
CELERY_ENABLE_UTC = False # Defina como False se CELERY_TIMEZONE estiver definido

"""# Configurações para o Celery Beat (agendador)
CELERY_BEAT_SCHEDULE = {
    # Exemplo de tarefa agendada (pode ser removida depois)
    'add-every-10-seconds': {
        'task': 'devices.tasks.debug_task_example', # Caminho para a sua tarefa
        'schedule': 10.0, # Executa a cada 10 segundos
        'args': ('Hello from Celery Beat!',)
    },
}"""

# Tarefa para verificar e despachar comandos agendados a cada minuto
CELERY_BEAT_SCHEDULE = {
'check-and-dispatch-scheduled-commands': {
        'task': 'devices.tasks.check_and_dispatch_scheduled_commands',
        'schedule': 60.0, # Executa a cada 60 segundos (1 minuto)
        'args': (),
    },
}


# settings.py

JAZZMIN_SETTINGS = {
    # Título do cabeçalho da página admin
    "site_header": "Controle IOT",

    # Título da aba do navegador
    "site_brand": "Controle dos IOT",

    # Logo no cabeçalho (pode ser um caminho para um arquivo estático ou URL)
    # "site_logo": "img/logo.png", # Exemplo: se você tiver uma imagem em static/img/logo.png

    # Texto de boas-vindas no canto superior direito
    "welcome_sign": "Bem-vindo ao Painel de Controle IOT",

    "site_title": "Controle IOT",  # Título na aba do navegador

    # Icones Font Awesome 6 (precisa instalar 'django-jazzmin[fontawesome]')
    # ou Font Awesome 5 (padrão)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "devices.comandosagendados": "fas fa-clock", # Exemplo: ajuste para seus modelos
        "devices.diasdasemana": "fas fa-calendar-alt",
        "devices.dispositivos": "fas fa-microchip",
        # Adicione ícones para outros modelos e apps conforme necessário
    },
    # Se você quiser usar Font Awesome 6, descomente e instale:
    # "default_icon_parents": "fas fa-chevron-circle-right",
    # "default_icon_children": "fas fa-circle",

    # Mostrar o menu lateral minimizado por padrão
    "navigation_expanded": True,

    # Mostrar o botão "View site" no cabeçalho
    "show_sidebar": False,

    # Cores do tema (existem vários temas pré-definidos)
    # Veja a documentação para mais opções: https://django-jazzmin.readthedocs.io/jazzmin_settings/
    "topbar_links": [
        {"name": "Suporte", "url": "https://github.com/farsil/django-jazzmin/issues", "new_window": True},
    ],
    
    "show_ui_builder": False, # Permite personalizar o tema na interface (apenas para desenvolvimento)
    "custom_css": None,
}

# Configurações adicionais para o UI Builder (opcional, mas útil para testar temas)
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark navbar-primary",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly", # Experimente outros temas como 'flatly', 'cerulean', 'cosmo', 'journal', 'litera', 'lumen', 'lux', 'materia', 'minty', 'pulse', 'sandstone', 'simplex', 'sketchy', 'slate', 'solar', 'spacelab', 'superhero', 'united', 'yeti'
    "dark_mode_theme": None, # Use um tema escuro específico se quiser
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

